spring:
  application:
    name: api_gateway_server
server:
  port: 8765
zuul:
  routes:
    usermicro:
      path: /user_micro/**
      serviceId: user_micro
    categorymicro:
      path: /category_micro/**
      serviceId: category_micro
    productmicro:
      path: /products_micro/**
      serviceId: products_micro
    ordersmicro:
      path: /orders_micro/**
      serviceId: orders_micro
  ignored-services: "*"
  sensitiveHeaders: Authorization,Cookie,Set-Cookie,User-Details
  ignored-headers: Access-Control-Allow-Headers,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Max-Age
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/info
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
